name: Sync with upstream

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Sync changes from upstream

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/TechWaveTW/test.git
          git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main --no-edit

      - name: Push changes to forked repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
