on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-22.04
    steps:
      - name: Sync with Upstream Repository
        uses: tgymnich/fork-sync@v1.8.0
        with:
          upstream_repository: owner/repo
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Changes to Forked Repositories
        run: |
          git remote add forked git@github.com:owner/repo.git
          git push forked
