on:
  push:
    branches:
      - main

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
      # Step 1: run a standard checkout action, provided by github
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
          ref: main

      # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
      - name: Pull upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_repository: open-sauced/goals-template
          upstream_branch: main
          target_branch: main                       # optional
          github_token: ${{ secrets.GITHUB_TOKEN }}
