name: Sync Forks

on:
  push:
    branches:
      - main

jobs:
  sync_forks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Sync forks
        uses: repo-sync/github-sync@v2
        with:
          source_repo: ${{ github.repository }}
          source_branch: main
          destination_token: ${{ secrets.FORK_SYNC_TOKEN }}
